import type { Metadata } from "next";
import localFont from "next/font/local";

const pingfangsc = localFont({
  src: "../assets/fonts/PingFangSC.ttf",
  variable: "--font-pingfangsc",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pingfangsc.variable}`}>
        {children}
      </body>
    </html>
  );
}
